### ISSUE TITLE
Autosend error

### ISSUE THREAD

**Issue by b1conrad** [Picolab/fully-sharded-database#96]
13:41:37.675Z [ERROR] http autosend error 
```
{ "rid":"io.picolabs.aca",
  "error":{
    "name":"Error","message":"Not allowed by channel policy",
    "stack":"Error: Not allowed by channel policy
             at assertEventPolicy (/usr/local/lib/node_modules/pico-engine/node_modules/pico-framework/dist/src/Channel.js:131:15)
             at Channel.assertEventPolicy (/usr/local/lib/node_modules/pico-engine/node_modules/pico-framework/dist/src/Channel.js:61:9)
             at PicoFramework.event (/usr/local/lib/node_modules/pico-engine/node_modules/pico-framework/dist/src/PicoFramework.js:140:17)
             at /usr/local/lib/node_modules/pico-engine/node_modules/pico-engine-core/dist/modules/http.js:103:43
             at runMicrotasks ()
             at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}

**Comment by b1conrad** [comment]
Dang it all. When throwing an error, please provide all of the information available at the time. I need to know the channel ID whose policy was too restrictive. How else can I open up its policy? If I don't know which channel this came in on?

**Comment by b1conrad** [comment]
A general rule emerges. Any ruleset that extends (uses as a module) `io.picolabs.aca` and that might raise the `didcomm: new_ssi_agent_wire_message` event needs to allow the `http:post` event in the channel policy of any channel it creates that might be used for that purpose.

**Comment by b1conrad** [comment]
Fix done in [this commit](https://github.com/Picolab/aries-cloudagent-pico/commit/f8de5ed7cb8bff0da405bd282b8f04925174b6fd).

But. How to deploy it? The ruleset is already installed in numerous participant picos, and in each one of those there is a channel with the too-narrow policy. A new installation should, theoretically fix the problem, so we'll need to arrange to install it in those picos that already have it.

The "theoretically" is that it uses [a technique](https://github.com/Picolab/aries-cloudagent-pico/blob/master/NEXT/io.picolabs.aca.basicmessage.krl#L90) that I have never seen before and haven't verified that it works. If it doesn't work, it'll lose all basicmessages already received (or sent for that matter).

Oh, and this issue doesn't belong here at all.

**Comment by b1conrad** [comment]
This was fixed a different way in the ACA-Pico repo. The fix here does no harm, but we don't need to worry about updating picos that have an older version of the `io.picolabs.aca.basicmessage` ruleset any more. Verified that the new fix works, and that it uses the main ECI instead of the one whose policy we widened (so the widening is now immaterial and unnecessary, but not harmful).
